<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-09 23:57
=======
# Generated by Django 3.0.6 on 2020-05-30 07:42
>>>>>>> 00b7560d221a17afc2f63807b5f895c7711d089f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(null=True, upload_to=''),
=======
            field=models.ImageField(blank=True, null=True, upload_to=''),
>>>>>>> 00b7560d221a17afc2f63807b5f895c7711d089f
        ),
    ]
