# Generated by Django 3.1.3 on 2020-12-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201204_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedItems',
        ),
    ]
