# Generated by Django 3.1.3 on 2020-12-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_saveditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
